### ISSUE TITLE
currentFeed not updating correctly after removing feed

### ISSUE THREAD

**Issue by bantuist** [GR4296/team-turtles42#18]

**Comment by bantuist** [comment]
I was trying to close this from the commit message, but I guess it doesn't close until merged into the default branch.

**Comment by psychometry** [comment]
I'm have the latest dev and I'm still getting errors if I have an empty feed or deleted feed

**Comment by bantuist** [comment]
Hey @psychometry, yeah I have to do a pull request first for you to see the changes. I'm writing some tests for my reducers and then I will submit it.
