### ISSUE TITLE
Optimize background image loading

### ISSUE THREAD

**Issue by bantuist** [GR4296/team-turtles42#2]
All I did was connect to the unsplash API and load a random image. If we continue to use unsplash, I think we should optimize load time or save image and only request new images at a set interval.

**Comment by GR4296** [comment]
That would be a good idea. We could either have it change everyday or with daylight/sunset times. The latter would be cool if we could find collections that differentiate between daytime and night time pictures.

**Comment by psychometry** [comment]
We can cache the image link to localStorage along with a Datetime string. You just check the localStorage to see if you have a link already cached and use the Datetime string to determine if you should retrieve a new image.

We can even pre-cache a collection of image links to further limit API request.

**Comment by bantuist** [comment]
Morning/Night images and localStorage sound good! It also seems like we can get the images on the React dev server fine, but the Chrome Extension new tab page doesn't seem to support `fetch`: `Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported`.

**Comment by bantuist** [comment]
False alarm about using `fetch`, I wasn't setting up my environment variables correctly before running `yarn run build`.

**Comment by bantuist** [comment]
This is resolved isn't it @psychometry ?

**Comment by psychometry** [comment]
Yes, it's been resolved
