### ISSUE TITLE
Find way to customize semantic-ui styling.

### ISSUE THREAD

**Issue by bantuist** [GR4296/team-turtles42#4]
I'm experimenting with customize Semantic-UI components to see much of a hassle it is... Perhaps the rule should be if it is easier to implement the component ourselves, don't use Semantic-UI if it makes customization a problem.

**Comment by psychometry** [comment]
After a few attempt, I find the semantic-ui-react components are difficult to customize style, therefore I'm using just regular Scss to style my components

**Comment by bantuist** [comment]
I agree @psychometry. I'm doing the same.
